# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-07 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loho', '0004_goods'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='loho_goods',
        ),
    ]
