# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-09 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loho', '0007_order_ordergoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='yh_price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
