# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loho', '0008_goods_yh_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
